### ISSUE TITLE
Configurable HTTP Client

### ISSUE THREAD

**Issue by polvalente** [tallarium/reverse_proxy_plug#115]
Are there any plans to support other HTTP Clients aside from HTTPoison?

The motivation behind this is that currently neither HTTPoison nor Hackney (which is the default pool) have good Telemetry events.

**Comment by mwhitworth** [comment]
One idea might be to move the library used to Tesla, which supports a number of different HTTP clients using [adapters](https://github.com/teamon/tesla#adapters).

**Comment by polvalente** [comment]
> One idea might be to move the library used to Tesla, which supports a number of different HTTP clients using [adapters](https://github.com/teamon/tesla#adapters).

Yes. As I see it, Tesla is really flexible in lots of regards (middlewares, clients, adapters...).

**Comment by victorolinasc** [comment]
Hi @mwhitworth ! Would a PR be welcome in this direction?

**Comment by mwhitworth** [comment]
> Hi @mwhitworth ! Would a PR be welcome in this direction?

Certainly @victorolinasc!

**Comment by polvalente** [comment]
@mwhitworth any pointers on what a PR on this should achieve?

HTTPoison and Tesla have two very distinct interfaces. IMO either we define a custom behaviour and custom structs that can be translated to/from both interfaces, or we could just ditch httpoison in a non-retrocompatible way.

**Comment by polvalente** [comment]
I'm working on a proposal for a retrocompatible implementation which allows a custom client to be passed.
I'll provide default adapters for HTTPoison and Tesla.

**Comment by Fedjmike** [comment]
Closing this, thanks to your earlier PR.
