### ISSUE TITLE
Stalling proxied requests

### ISSUE THREAD

**Issue by xadhoom** [tallarium/reverse_proxy_plug#132]
Sometime buffered & already parsed requests stalls.

This because reverse_proxy_plug tries to read an already read body, and Plug.Conn will wait on the underlying adapter for more data to come.

Looking into the code, reverse_proxy_plug uses raw_body only if body is empty which is not optimal in such cases (also goes in contrast on what README.md states).

I've sent the PR https://github.com/tallarium/reverse_proxy_plug/pull/131 which addresses this case.

**Comment by mwhitworth** [comment]
Thanks for this and other PRs @xadhoom - very much appreciated!

**Comment by mwhitworth** [comment]
#131 now merged
