### ISSUE TITLE
Make request header normalization configurable

### ISSUE THREAD

**Issue by yanomateus** [tallarium/reverse_proxy_plug#150]
Hi there!

Request headers are always downcased when sent upstream [here](https://github.com/tallarium/reverse_proxy_plug/blob/master/lib/reverse_proxy_plug.ex#L298).

```elixir
  defp normalize_headers(headers) do
    headers
    |> downcase_headers
    |> remove_hop_by_hop_headers
  end
```

Could the casing be configurable? The upstream we relay requests to through this plug performs case sensitive matching to consume some headers, dropping the ones which have been downcased.

Thanks!

**Comment by mwhitworth** [comment]
Released in [v2.4.0](https://github.com/tallarium/reverse_proxy_plug/releases/tag/v2.4.0)
