### ISSUE TITLE
Finch Adapter?

### ISSUE THREAD

**Issue by suprafly** [tallarium/reverse_proxy_plug#164]
Not so much an issue, but I wanted to see if there is a desire for a `Finch` adapter? I have a simple one working, and would be happy to make a PR. I did not see any contribution guidelines, so I figured it would be best to open an issue first.

The latest version of `Phoenix` ships with `Finch` by default, so having an adapter means one less dependency users of your library will need if they are coming from `Phoenix`.

Cheers.

**Comment by mwhitworth** [comment]
More adapters are no bad thing. Happy to see a PR for this

**Comment by mwhitworth** [comment]
I put together an initial version of a Finch adapter.

It needs more testing, and I'd like to support third-party library versions as early as possible (given the general nature of this library) - so I'll make another pass at this before merging and releasing.

**Comment by mwhitworth** [comment]
Buffer response mode is now supported - work to support streaming responses will be tracked in https://github.com/tallarium/reverse_proxy_plug/issues/204
