### ISSUE TITLE
Issue with duplicate headers in response.

### ISSUE THREAD

**Issue by Harper04** [tallarium/reverse_proxy_plug#165]
Hi, 
i would like to point an issue i found while proxying for example keycloak.
Keycloak uses the "set-cookie"-Header multiple times. 
In streaming mode reverse proxy plug does not pass on these headers because it is reducing on the response headers using Conn.put_resp_header which will update existing headers.
In buffering mode it works as there it is just passed on.

**Comment by mwhitworth** [comment]
#168 address this issue
