### ISSUE TITLE
Broken in Bandit (also silently in Cowboy)

### ISSUE THREAD

**Issue by andyleclair** [tallarium/reverse_proxy_plug#175]
Hello! Your code has a bug, right here: https://github.com/tallarium/reverse_proxy_plug/blob/master/lib/reverse_proxy_plug.ex#L382

You are ignoring the `_conn` here, however, you _must_ carry that `conn` forward. This causes subtle silent failures under Cowboy that become LOUD failures under Bandit. You can see what the failures look like here: https://github.com/mtrudel/bandit/issues/294

I believe I've correctly traced errors to this plug, which exactly has the bug described.

**Comment by mwhitworth** [comment]
Absolutely. I will address this and issue another release

**Comment by mwhitworth** [comment]
Released in [v2.3.1](https://github.com/tallarium/reverse_proxy_plug/releases/tag/v2.3.1)
