### ISSUE TITLE
Question: The client adapter does not support streaming responses. Please use :buffer response mode.

### ISSUE THREAD

**Issue by dersmon** [tallarium/reverse_proxy_plug#196]
Thank you for this. 

This is probably more of a documentation issue: I am trying to use [callbacks](https://github.com/tallarium/reverse_proxy_plug?tab=readme-ov-file#callbacks-for-responses-in-streaming-mode). I get the error mentioned above, while having configured the HTTPoison adapter:

```
config :reverse_proxy_plug, :http_client, ReverseProxyPlug.HTTPClient.Adapters.HTTPoison
```
with
```
{:httpoison, "~> 2.2.1"},
{:reverse_proxy_plug, "~> 2.4.0"},
```

Which adapter should I choose for the response callbacks?

**Comment by dersmon** [comment]
Hm, downgrading to version resolved the issue.

**Comment by mwhitworth** [comment]
Yes - this behaviour seems very similar to the issue discussed in #193.

Would you mind trying with v2.4.1 - released just now - which should contain a fix for this issue?

**Comment by dersmon** [comment]
Works, thank you very much for your quick update.
