### ISSUE TITLE
Can't seem to configure response_mode: :buffer

### ISSUE THREAD

**Issue by alexslade** [tallarium/reverse_proxy_plug#226]
Goal: set up buffered responses so I can modify the response request 

Problem: setting `response_mode: :buffer` causes an error (see below). 

Debug steps done so far: I've been digging into the project source, and stacktrack for a little while, but I haven't been able to understand the issue yet. Hopefully I'm missing something obvious.  
 
Repro: Below I include a full livebook here that you can replay to verify the issue. The req request works if response_mode is not set, or set to `:stream`. 

````
# Intercepting Server

```elixir
Mix.install(
  [
    {:plug, "~> 1.16"},
    {:kino, "~> 0.12.3"},
    {:bandit, "~> 1.5"},
    {:req, "~> 0.5.0"},
    {:reverse_proxy_plug, "~> 3.0"}
  ],
  config: [
    reverse_proxy_plug: [http_client: ReverseProxyPlug.HTTPClient.Adapters.Req]
  ]
)
```

## Section

```elixir
defmodule Router do
  use Plug.Router

  plug(:match)
  plug(:dispatch)

  forward("/bar",
    to: ReverseProxyPlug,
    upstream: "https://webhook.site/dc48d1e7-40b7-4d19-8707-3482e783b939",
    response_mode: :buffer
  )
end

Kino.start_child!({Bandit, plug: Router, port: 6789})
```

<!-- livebook:{"output":true} -->

```

22:35:26.955 [info] Running Router with Bandit 1.5.3 at 0.0.0.0:6789 (http)

```

<!-- livebook:{"output":true} -->

```
#PID<0.15056.0>
```

```elixir
Req.get!("http://0.0.0.0:6789/bar")
```

<!-- livebook:{"output":true} -->

```

22:35:43.990 [error] ** (Plug.Conn.WrapperError) ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a binary

    (stdlib 5.1.1) :binary.match(["no-cache, private"], ["\n", "\r", <<0>>])
    (plug 1.16.0) lib/plug/conn.ex:1935: Plug.Conn.validate_header_key_value!/2
    (plug 1.16.0) lib/plug/conn.ex:927: anonymous fn/3 in Plug.Conn.prepend_resp_headers/2
    (elixir 1.15.7) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug 1.16.0) lib/plug/conn.ex:925: Plug.Conn.prepend_resp_headers/2
    (reverse_proxy_plug 3.0.0) lib/reverse_proxy_plug.ex:181: ReverseProxyPlug.process_response/4
    (plug 1.16.0) lib/plug.ex:169: Plug.forward/4
    Library/Caches/mix/installs/elixir-1.15.7-erts-14.1.1/2a0cf5cf8412517d2238104f64b4db9e/deps/plug/lib/plug/router.ex:246: anonymous fn/4 in Router.dispatch/2


22:35:43.992 [error] retry: got response with status 500, will retry in 1000ms, 3 attempts left

```

````

**Comment by mwhitworth** [comment]
It's a change in [req 0.4.0](https://github.com/wojtekmach/req/blob/main/CHANGELOG.md#v040-2023-09-01) to represent headers as maps, with even single individual values wrapped in a list. I focused my testing on streaming responses in req >= 0.4.0, so I missed this.

I'll release a fix for this (normalizing headers at the `Req` adapter level, most likely) and release 3.0.1 shortly.

**Comment by mwhitworth** [comment]
A fix for this, which normalises the response headers to a list of `{binary, binary}` tuples to match the response header format from other adapters, is in [v3.0.1](https://github.com/tallarium/reverse_proxy_plug/releases/tag/v3.0.1)
