### ISSUE TITLE
The `host` header is not properly formed when is over a non-standard port

### ISSUE THREAD

**Issue by GermanDZ** [tallarium/reverse_proxy_plug#26]
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host, the host header should (must?) not include the port number when the port is the default.

i.e:

For `http://web.example.com:80`, the host should be `web.example.com`
For `http://special.port.com:666`, the host should be `special.port.com:666`

Right now if the plug is configured with upstream `http://special.port.com:666` and not `host` header is passed in the request, the host header is generated as `special.port.com`. The expected  value is `special.port.com:666`

**Comment by GermanDZ** [comment]
I will write some test, propose a fix for this cases and submit the PR. But I can't promise an ETA.

**Comment by msz** [comment]
Closed in #27.
