### ISSUE TITLE
Is there any support for the X-Forwarded-For header ?

### ISSUE THREAD

**Issue by lud** [tallarium/reverse_proxy_plug#81]

**Comment by mwhitworth** [comment]
Could you provide an example of what you would like to achieve? Given it involves modifying the headers, it could be achieved via a separate plug.

**Comment by lud** [comment]
Wow, it has been a while!

I cannot remember exactly why I needed this header. I was trying to create a simple proxy for 3 PHP apps that were served on ports 8000, 8001, 8002, and for some reason I needed to serve the 3 apps on a single port. I can't even remember why I needed the IP on the far side.

**Comment by ngeraedts** [comment]
Hi! I'd like to see if we can reopen this ticket. Applications may need to know the IP address of the original request, and proxies should be adding or updating this header accordingly when connecting to the upstream server. 

I'd be happy to provide the MR - I've already got the functionality working on a local copy.

**Comment by mwhitworth** [comment]
Sure - I suppose it can be argued that it should be part of the innate behaviour of a reverse proxy
