### ISSUE TITLE
Performance related question

### ISSUE THREAD

**Issue by 9to1url** [tallarium/reverse_proxy_plug#86]
Thanks for your good jobs, I really like the plug.

I couldn't found any place you mentioned support, could you advise on this?

For the performance question, do I need to do some extra works to make it scalable like Phoenix or it just works out of box with this one line adding to my Router:

```
  forward("/hls", to: ReverseProxyPlug, upstream: "http://127.0.0.1:8080/hls")
```

I plan to to proxy RTMP HLS video streaming traffic.

**Comment by 9to1url** [comment]
The performance is great! Thank you. I use a 2 core 4GB ram machine, and Max network at 300Mb/s, for long hours without any issue.
The only thing I can observe is: Nginx CPU usage keep around 4%, the proxy CPU usage from 10% to 60% up and down.

**Comment by mwhitworth** [comment]
> I couldn't found any place you mentioned support, could you advise on this?

We don't offer support for this library, though we'll attempt to address issues here to the best of our ability.

> The performance is great! Thank you.

Glad to hear it!
